# Generated by Django 2.1.3 on 2018-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='about_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='trip',
            name='recomendation',
            field=models.CharField(max_length=1000),
        ),
    ]
