export const ACTION_GET_TRIPS_STARTED = "GET_TRIPS_STARTED";
export const ACTION_GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const ACTION_GET_TRIPS_FAILED = "GET_TRIPS_FAILED";

export const ACTION_GET_REVIEWS_STARTED = "GET_REVIEWS_STARTED";
export const ACTION_GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const ACTION_GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";

export const ACTION_POST_REVIEW_STARTED = "POST_REVIEW_STARTED";
export const ACTION_POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const ACTION_POST_REVIEW_FAILED = "POST_REVIEW_FAILED";

export const ACTION_GET_DETAILS_STARTED = "GET_DETAILS_STARTED";
export const ACTION_GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const ACTION_GET_DETAILS_FAILED = "GET_DETAILS_FAILED";

